// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateList(arg1) {
  return window['go']['main']['App']['CreateList'](arg1);
}

export function CreateSubTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSubTask'](arg1, arg2, arg3);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteList(arg1) {
  return window['go']['main']['App']['DeleteList'](arg1);
}

export function DeleteSubTask(arg1) {
  return window['go']['main']['App']['DeleteSubTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAllLists() {
  return window['go']['main']['App']['GetAllLists']();
}

export function GetAllSubTasks() {
  return window['go']['main']['App']['GetAllSubTasks']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetList(arg1) {
  return window['go']['main']['App']['GetList'](arg1);
}

export function GetSubTask(arg1) {
  return window['go']['main']['App']['GetSubTask'](arg1);
}

export function GetSubTasksByTaskID(arg1) {
  return window['go']['main']['App']['GetSubTasksByTaskID'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTasksByListID(arg1) {
  return window['go']['main']['App']['GetTasksByListID'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ToggleSubTaskCompletion(arg1) {
  return window['go']['main']['App']['ToggleSubTaskCompletion'](arg1);
}

export function ToggleTaskCompletion(arg1) {
  return window['go']['main']['App']['ToggleTaskCompletion'](arg1);
}

export function UpdateList(arg1, arg2) {
  return window['go']['main']['App']['UpdateList'](arg1, arg2);
}

export function UpdateSubTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSubTask'](arg1, arg2, arg3, arg4);
}

export function UpdateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4);
}
