// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';

export function CreateList(arg1:string):Promise<server.List>;

export function CreateSubTask(arg1:string,arg2:string):Promise<server.SubTask>;

export function CreateTask(arg1:string,arg2:string):Promise<server.Task>;

export function DeleteList(arg1:string):Promise<void>;

export function DeleteSubTask(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetAllLists():Promise<Array<server.List>>;

export function GetAllSubTasks():Promise<Array<server.SubTask>>;

export function GetAllTasks():Promise<Array<server.Task>>;

export function GetList(arg1:string):Promise<server.List>;

export function GetSubTask(arg1:string):Promise<server.SubTask>;

export function GetSubTasksByTaskID(arg1:string):Promise<Array<server.SubTask>>;

export function GetTask(arg1:string):Promise<server.Task>;

export function GetTasksByListID(arg1:string):Promise<Array<server.Task>>;

export function ToggleSubTaskCompletion(arg1:string):Promise<server.SubTask>;

export function ToggleTaskCompletion(arg1:string):Promise<server.Task>;

export function UpdateList(arg1:string,arg2:string):Promise<server.List>;

export function UpdateSubTask(arg1:string,arg2:string,arg3:boolean):Promise<server.SubTask>;

export function UpdateTask(arg1:string,arg2:string,arg3:boolean):Promise<server.Task>;
